# Generated by Django 6.0.3 on 2026-03-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Топтомдун аталышы')),
                ('pieces', models.IntegerField(verbose_name='Даана саны')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Баасы')),
                ('image', models.ImageField(upload_to='sets/', verbose_name='Сүрөтү')),
                ('whatsapp_msg', models.TextField(verbose_name='WhatsApp билдирүүсү')),
            ],
            options={
                'verbose_name': 'Топтом',
                'verbose_name_plural': 'Топтомдор',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
