# Generated by Django 6.0.3 on 2026-03-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productset_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productset',
            name='ready_time',
            field=models.CharField(default='2 саат', help_text='Мисалы: 2-3 саат же 1 күн', max_length=100, verbose_name='Даяр болуу убактысы'),
        ),
        migrations.AlterField(
            model_name='productset',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Баасы (сом)'),
        ),
        migrations.AlterField(
            model_name='productset',
            name='whatsapp_msg',
            field=models.TextField(help_text="Кардар 'Заказ берүү' баскычын басканда сизге келе турган текст", verbose_name='WhatsApp билдирүүсү'),
        ),
    ]
