# Generated by Django 6.0.3 on 2026-03-31 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productset_ready_time_alter_productset_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productset',
            name='video',
            field=models.FileField(blank=True, help_text='Телефондон галереядан тандап жүктөсөңүз болот (mp4, mov сунушталат)', null=True, upload_to='sets/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'])], verbose_name='Видеосу'),
        ),
        migrations.AlterField(
            model_name='productset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sets/images/', verbose_name='Сүрөтү'),
        ),
    ]
