# Generated by Django 6.0.3 on 2026-04-01 08:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productset_video_alter_productset_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Музыканын аталышы (мис: Luxury Jazz)')),
                ('audio_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='MP3 файл')),
                ('is_active', models.BooleanField(default=False, verbose_name='Азыр ушул музыка ойносунбу?')),
            ],
            options={
                'verbose_name': 'Фондук музыка',
                'verbose_name_plural': 'Фондук музыкалар',
            },
        ),
        migrations.AlterField(
            model_name='productset',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Сүрөтү'),
        ),
        migrations.AlterField(
            model_name='productset',
            name='ready_time',
            field=models.CharField(default='2 саат', max_length=100, verbose_name='Даяр болуу убактысы'),
        ),
        migrations.AlterField(
            model_name='productset',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Видеосу'),
        ),
        migrations.AlterField(
            model_name='productset',
            name='whatsapp_msg',
            field=models.TextField(verbose_name='WhatsApp билдирүүсү'),
        ),
    ]
